feedback/urls.py
from django.conf.urls import url
from . import views

app_name = 'feedback'
urlpatterns = [
    url(r'^$', views.send, name='send'),
]

home/urls.py
from django.conf.urls import url
from . import views

app_name = 'home'
urlpatterns = [
    url(r'^$', views.index, name='index'),
]

phones/urls.py
from django.conf.urls import url
from . import views

app_name = 'phones'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^(?P<pk>[0-9]+)/order$', views.order, name='order'),
]

retrophone/urls.py
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin

from retrophone import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('home.urls')),
    url(r'^feedback/', include('feedback.urls')),
    url(r'^shops/', include('shops.urls')),
    url(r'^phones/', include('phones.urls')),
    url(r'^search/', include('search.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

search/urls.py
from django.conf.urls import url
from . import views

app_name = 'search'
urlpatterns = [
    url(r'^$', views.search, name='search'),
]

shops/urls.py
from django.conf.urls import url
from . import views

app_name = 'shops'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
]

feedback/models.py
from django.db import models

# Create your models here.

home/models.py
from django.db import models

# Create your models here.

phones/models.py
import os

from django.db import models


def get_image_path(instance, filename):
    return os.path.join('phones', str(instance.id), filename)


class Phone(models.Model):
    name = models.CharField(max_length=255)
    desc = models.TextField()
    short_desc = models.TextField()
    photo = models.ImageField(upload_to=get_image_path, blank=True, null=True)
    price = models.IntegerField()

    def __str__(self):
        return self.name

search/models.py
from django.db import models

# Create your models here.

shops/models.py
import os

from django.db import models


def get_image_path(instance, filename):
    return os.path.join('shops', str(instance.id), filename)


class Shop(models.Model):
    name = models.CharField(max_length=255)
    desc = models.TextField()
    photo = models.ImageField(upload_to=get_image_path, blank=True, null=True)

    def __str__(self):
        return self.name

feedback/views.py
import json

from django.core.mail import send_mail
from django.http import Http404
from django.http import HttpResponse
from django.template.loader import render_to_string

from retrophone.private_settings import EMAIL_HOST_USER, EMAIL_TO


def send(request):
    if request.method != 'POST':
        raise Http404

    context = {
        'message': json.loads(request.body.decode('utf-8'))['message'],
    }
    send_mail(
        'Сообщение с формы обратной связи',
        render_to_string('feedback/email.txt', context),
        EMAIL_HOST_USER,
        [EMAIL_TO],
        fail_silently=False,
        html_message=render_to_string('feedback/email.html', context)
    )

    return HttpResponse('Ok')

home/views.py
from django.shortcuts import render


def index(request):
    return render(request, 'home/index.html')

phones/views.py
import json
from datetime import datetime, timedelta

from django.core.mail import send_mail
from django.http import Http404
from django.http import HttpResponse
from django.shortcuts import get_object_or_404
from django.template.loader import render_to_string
from django.views import generic

from phones.models import Phone
from retrophone.private_settings import EMAIL_HOST_USER
from retrophone.private_settings import EMAIL_TO


class IndexView(generic.ListView):
    template_name = 'phones/index.html'
    context_object_name = 'phones'

    def get_queryset(self):
        return Phone.objects.all()


class DetailView(generic.DetailView):
    model = Phone
    template_name = 'phones/detail.html'

    def render_to_response(self, context, **response_kwargs):
        date = datetime.now() + timedelta(days=3)
        context['date'] = date.strftime('%Y-%m-%d')
        return super().render_to_response(context, **response_kwargs)


def order(request, pk):
    if request.method != 'POST':
        raise Http404

    book = get_object_or_404(Phone, pk=pk)

    payload = json.loads(request.body.decode('utf-8'))
    context = {
        'email': payload['email'],
        'bookName': book.name,
        'amount': payload['amount'],
    }

    send_mail(
        'Заказ телефона',
        render_to_string('phones/email.txt', context),
        EMAIL_HOST_USER,
        [EMAIL_TO],
        fail_silently=False,
        html_message=render_to_string('phones/email.html', context)
    )

    return HttpResponse('Ok')

search/views.py
from django.db.models import Q
from django.shortcuts import render
from django.urls import reverse

from phones.models import Phone


def search(request):
    query = request.GET['query']
    results = []

    if query:
        search_results = Phone.objects.filter(
            Q(name__icontains=query)
            | Q(desc__icontains=query)
        )

        for result in search_results:
            results.append({
                'url': reverse('phones:detail', args=[result.id]),
                'header': result.name,
            })

    return render(request, 'search/results.html', {
        'query': query,
        'results': results,
    })

shops/views.py
from django.views import generic

from shops.models import Shop


class IndexView(generic.ListView):
    template_name = 'shops/index.html'
    context_object_name = 'shops'

    def get_queryset(self):
        return Shop.objects.all()

feedback/templates/feedback/email.html
<h2>Форма обратной связи</h2>
<div>
    Пользователь с оставил следующее сообщение в форме обратной связи:
    <p>
        "{{ message }}"
    </p>
</div>

home/templates/home/index.html
{% extends 'base.html' %}

{% block content %}
    <div class="row">
        <div class="col-sm-2">ha</div>
        <div class="col-sm-8">
            <div class="home-banner">
                <p>Надоели современные телефоны на iOS и Android?</p>
                <p>Устали заряжать телефон по 2 раза в день?</p>
                <p>Телефон не помещается в карман?</p>
                <p>Тогда вы зашли по адресу!</p>
            </div>
        </div>
        <div class="col-sm-2">ho</div>
    </div>
    <p class="home-slogan">
        Здесь вы можете найти и купить новые телефоны из прошлого!<br>
        Выделись из толпы и купи модный раритетный телефон уже сейчас!
    </p>
    <div class="home-buttons">
        <a href="{% url 'phones:index' %}" class="btn btn-primary home-btn">
            Онлайн каталог
        </a>
        <a href="{% url 'shops:index' %}" class="btn btn-primary home-btn">
            Наши магазины
        </a>
    </div>
{% endblock %}

phones/templates/phones/detail.html
{% extends 'base.html' %}

{% block content %}
    {% include 'phones/modal.html' %}

    <div class="row">
        <div class="col-sm-3">
            <img src="{{ phone.photo.url }}" alt="{{ phone.name }}"
                 class="phone-image">
            <p class="phone-price">{{ phone.price }} руб.</p>
            <a href="#" class="btn btn-primary" data-toggle="modal"
               data-target="#phone-modal">
                Оформить заявку
            </a>
        </div>
        <div class="col-sm-9">
            <h2>{{ phone.name }}</h2>
            <p class="phone-desc">{{ phone.desc }}</p>
        </div>
    </div>
{% endblock %}

phones/templates/phones/email.html
<p>
    Пользователь с адресом электронной почты {{ email }} заказал книгу
    с названием "{{ bookName }}" в количестве {{ amount }}
</p>

phones/templates/phones/index.html
{% extends 'base.html' %}

{% load chunks %}

{% block content %}
    {% if phones %}
        {% for chunk in phones|chunks:3 %}
        <div class="row">
            {% for phone in chunk %}
                <div class="col-sm-4 phone-card">
                    <div class="col-sm-3">
                        <img src="{{ phone.photo.url }}" alt="{{ phone.name }}"
                             class="phone-card-image">
                    </div>
                    <div class="col-sm-9">
                        <h2>{{ phone.name }}</h2>
                        <p class="phone-card-desc">{{ phone.short_desc }}</p>
                        <a href="{% url 'phones:detail' phone.id %}"
                           class="btn btn-primary">
                            Показать
                        </a>
                        <p class="phone-card-price">{{ phone.price }} руб.</p>
                    </div>
                </div>
            {% endfor %}
        </div>
        {% endfor %}
    {% else %}
        <p>Пока что нет ни одного телефона</p>
    {% endif %}
{% endblock %}

phones/templates/phones/modal.html
<div class="modal fade" id="phone-modal" tabindex="-1" role="dialog"
     aria-labelledby="phone-modal-label">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"
                        aria-label="Close"><span
                    aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="phone-modal-label">
                    Оформление заказа: {{ phone.name }}
                </h4>
            </div>
            <div class="modal-body">
                <form id="phone-modal-form">
                    <input type="hidden" id="phone-modal-price"
                           value="{{ phone.price }}">
                    <div class="form-group">
                        <label for="phone-modal-name">Имя</label>
                        <input type="text" class="form-control"
                               id="phone-modal-name" required>
                    </div>
                    <div class="form-group">
                        <label for="phone-modal-lastname">Фамилия</label>
                        <input type="text" class="form-control"
                               id="phone-modal-lastname" required>
                    </div>
                    <div class="form-group">
                        <label for="phone-modal-surname">Отчество</label>
                        <input type="text" class="form-control"
                               id="phone-modal-surname" required>
                    </div>
                    <div class="form-group">
                        <label for="phone-modal-phone">Телефон</label>
                        <input type="text" class="form-control"
                               id="phone-modal-phone" required>
                    </div>
                    <div class="form-group">
                        <label for="phone-modal-email">Email</label>
                        <input type="email" class="form-control"
                               id="phone-modal-email" required>
                    </div>
                    <div class="form-group">
                        <label for="phone-modal-addr">Адрес доставки</label>
                        <input type="text" class="form-control"
                               id="phone-modal-addr" required>
                    </div>
                    <div class="form-group">
                        <label for="phone-modal-date">Дата доставки</label>
                        <input type="date" class="form-control"
                               id="phone-modal-date"
                               min="{{ date }}" value="{{ date }}" required>
                    </div>
                    <div class="form-group">
                        <label for="phone-modal-amount">Количество</label>
                        <input type="number" min="1" class="form-control"
                               id="phone-modal-amount" value="1" required>
                    </div>
                </form>
                <div class="alert alert-danger collapse"
                     id="phone-modal-error"></div>
                <div class="alert alert-info collapse"
                     id="phone-modal-info"></div>
            </div>
            <div class="modal-footer">
                <span>
                    Итого к оплате:
                    <span id="phone-modal-sum">{{ phone.price }}</span>
                    руб.
                </span>
                <button type="button" class="btn btn-default"
                        data-dismiss="modal">
                    Отменить
                </button>
                <button type="button" class="btn btn-primary"
                        id="phone-order">
                    Купить
                </button>
            </div>
        </div>
    </div>
</div>

search/templates/search/results.html
{% extends 'base.html' %}

{% block content %}
    <div class="page-header">
        <h1>Результаты поиска по запросу "{{ query }}"</h1>
    </div>

    {% if results %}
        {% for result in results %}
            <div class="panel panel-default">
                <div class="panel-body">
                    <h2>
                        <a href="{{ result.url }}">{{ result.header }}</a>
                    </h2>
                </div>
            </div>
        {% endfor %}
    {% else %}
        <p>Ничего не нашлось</p>
    {% endif %}
{% endblock %}

shops/templates/shops/index.html
{% extends 'base.html' %}

{% block content %}
    {% if shops %}
        {% for shop in shops %}
            <div class="row shop">
                <div class="col-sm-3">
                    <img src="{{ shop.photo.url }}" alt="{{ shop.name }}"
                         class="shop-image">
                </div>
                <div class="col-sm-9">
                    <h3>{{ shop.name }}</h3>
                    <p class="shop-desc">{{ shop.desc }}</p>
                </div>
            </div>
        {% endfor %}
    {% else %}
        <p>Пока что нет ни одного магазина</p>
    {% endif %}
{% endblock %}

templates/base.html
{% load static %}

<!doctype html>
<html lang="ru">

<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap/dist/css/bootstrap.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}" />

    <title>{% block title %}Retrophone{% endblock %}</title>
</head>

<body>
{% csrf_token %}

<div class="container">
    {% include 'navbar.html' %}
    {% include 'messages.html' %}
    {% include 'feedback-modal.html' %}
    {% block content %}{% endblock %}
</div>

<script src="{% static 'jquery/dist/jquery.js' %}"></script>
<script src="{% static 'bootstrap/dist/js/bootstrap.js' %}"></script>
<script src="{% static 'axios/dist/axios.js' %}"></script>
<script src="{% static 'app.js' %}"></script>
</body>
</html>

templates/feedback-modal.html
<div class="modal fade" id="feedback-modal" tabindex="-1" role="dialog"
     aria-labelledby="feedback-modal-label">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"
                        aria-label="Close"><span
                    aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="feedback-modal-label">
                    Напишите нам, и мы ответим на все интересующие вас вопросы
                    незамедлительно
                </h4>
            </div>
            <div class="modal-body">
                <textarea name="message" id="feedback-message" cols="30"
                          rows="10" placeholder="Введите ваше сообщение"
                          class="form-control"></textarea>
                <div class="alert alert-danger collapse"
                     id="feedback-message-error"></div>
                <div class="alert alert-info collapse"
                     id="feedback-message-info"></div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default"
                        data-dismiss="modal">
                    Отменить
                </button>
                <button type="button" class="btn btn-primary"
                        id="feedback-send">
                    Отправить
                </button>
            </div>
        </div>
    </div>
</div>

templates/messages.html
{% if messages %}
    {% for message in messages %}
        <div class="alert{% if message.tags %} alert-{{ message.tags }}{% endif %}">
            {{ message }}
        </div>
    {% endfor %}
{% endif %}

templates/navbar.html
<nav class="navbar navbar-default">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed"
                    data-toggle="collapse"
                    data-target="#app-navbar-collapse" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/">Ретрофон</a>
        </div>

        <div class="collapse navbar-collapse" id="app-navbar-collapse">
            <ul class="nav navbar-nav">
                <li><a href="/">Главная</a></li>
                <li>
                    <a href="#" data-toggle="modal"
                       data-target="#feedback-modal">
                        Обратная связь
                    </a>
                </li>
            </ul>

            <form class="navbar-form navbar-right"
                  action="{% url 'search:search' %}" method="GET">
                <div class="form-group">
                    <input type="text" class="form-control"
                           placeholder="Поиск по сайту" name="query">
                </div>

                <button type="submit" class="btn btn-default">Искать</button>
            </form>
        </div>
    </div>
</nav>